//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScraperLinkedInServer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceSetting
    {
        public int Id { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public int IntervalType { get; set; }
        public int IntervalValue { get; set; }
        public int CompanyBatchSize { get; set; }
        public int ProfileBatchSize { get; set; }
        public int AccountId { get; set; }
    
        public virtual IntervalType IntervalType1 { get; set; }
        public virtual Account Account { get; set; }
    }
}
