//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScraperLinkedInServer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Job { get; set; }
        public string ProfileUrl { get; set; }
        public string AllSkills { get; set; }
        public int ExecutionStatusID { get; set; }
        public int CompanyID { get; set; }
        public int ProfileStatusID { get; set; }
        public System.DateTime DateСreation { get; set; }
        public int AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Company Company { get; set; }
        public virtual ExecutionStatus ExecutionStatus { get; set; }
        public virtual ProfileStatus ProfileStatus { get; set; }
    }
}
